services:
  - type: worker
    name: supabase-monitor
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python supabase_monitor.py
    plan: free
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false